# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP app to Azure Web App - PxPortal

env: 
    slnfile: PCAxis.PX-Web.sln
    outputdir: './toDeploy'

on:
  push:
    branches:
      - master
      - hakk4ssbv1
  workflow_dispatch:

jobs:

  build:
    runs-on: windows-latest
  

    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        run: nuget restore ${{env.slnfile}}

      - name: Publish to folder
        run: msbuild  ${{env.slnfile}} /nologo /verbosity:m /p:Configuration=Release /t:Publish /p:outdir=${{env.GITHUB_WORKSPACE}}/toDeploy
        #/verbosity:d

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: ASP-app
          path: '.'

  #deploy:
  #  runs-on: windows-latest
  #  needs: build
  #  environment:
  #    name: 'Production'
  #    url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

  #  steps:
  #    - name: Download artifact from build job
  #      uses: actions/download-artifact@v2
  #      with:
  #        name: ASP-app

  #    - name: Deploy to Azure Web App
  #      id: deploy-to-webapp
  #      uses: azure/webapps-deploy@v2
  #      with:
  #        app-name: 'PxPortal'
  #        slot-name: 'Production'
  #        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_23A0F761776845CCB79FF53F9F94ADD2 }}
  #        package: .
