# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy to Azure px2v48

env: 
    slnfile: PCAxis.PX-Web.sln

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  build:
    runs-on: windows-latest
  
    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        run: nuget restore PCAxis.PX-Web.sln

      - name: Publish to folder
        run: msbuild PCAxis.PX-Web.sln /nologo /verbosity:m /p:DeployOnBuild=true /p:Configuration=Debug /p:_PackageTempDir="${{ github.workspace }}\to_deploy\"
        
      - name: Copy Azure Configfiles
        run: |
          cp TheAzureConfigFiles/databases.config to_deploy/.
          cp TheAzureConfigFiles/Web.config to_deploy/.
          cp TheAzureConfigFiles/setting.config to_deploy/.
             
      - name: Change title
        run: sed -i 's/PxWeb 2021 v1/PxWeb 2021 from pullrequest Dev2/g' to_deploy/Resources/Languages/pxlang.xml

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: ASP-app
          path: '${{ github.workspace }}\to_deploy\**'

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: ASP-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'px2v48'
          slot-name: 'Dev2'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CF43236341DF4B4E9CA8E0E3871310A2 }}
          package: .
